apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-github-release-generator
spec:
  generators:
    - plugin:
        configMapRef:
          name: argocd-github-release-generator
        input:
          parameters:
            repository: "dagger/dagger"
            min_release: v0.9.8

        # When using a Plugin generator, the ApplicationSet controller polls every 
        # `requeueAfterSeconds` interval (defaulting to every 30 minutes) to detect changes.
        requeueAfterSeconds: 10

  template:
    metadata:
      name: "argocd-github-release-generator-{{hello}}"
    spec:
      source:
        repoURL: https://github.com/matipan/argocd-github-release-generator
        targetRevision: main
        path: k8s/manifests
        kustomize:
          nameSuffix: -{{hello}}
          namespace: "services"
          forceCommonLabels: true
          images:
            - ghcr.io/matipan/argocd-github-release-generator:test
          patches:
            - target:
                kind: Service
                name: argocd-github-release-generator
              patch: |-
                kind: Service
                metadata:
                  name: argocd-github-release-generator-{{name}}
            - target:
                kind: Deployment
                name: argocd-github-release-generator
              patch: |-
                kind: Deployment
                metadata:
                  name: argocd-github-release-generator-{{name}}
                spec:
                  template:
                    spec:
                      containers:
                        name: argocd-github-release-generator
                        env:
                          - name: DAGGER_VERSION
                            value: {{name}}
                          - name: DAGGER_VERSION_SHA
                            value: {{commit.sha}}
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: services
