apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-github-release-generator
  name: argocd-github-release-generator
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-github-release-generator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argocd-github-release-generator
    spec:
      containers:
      - env:
        - name: ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              key: plugin.argocd-github-release-generator.token
              name: argocd-github-release-generator
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              key: plugin.argocd-github-release-generator.github_pat
              name: argocd-github-release-generator
        image: ghcr.io/matipan/argocd-github-release-generator:test
        imagePullPolicy: Always
        name: argocd-github-release-generator
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 100Mi
