apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-release-generator
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  plugin.argocd-github-release-generator.token: "c2VjcmV0Cg=="
