apiVersion: v1
kind: Service
metadata:
  name: argocd-github-release-generator
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app: argocd-github-release-generator
  ports:
    - port: 8080
      name: http
      targetPort: 8080
